# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6564bde8656d2f52315e045def2813823c33e4fbdc93a03826b61a065785a8bbfac3e98a4932199a5dd34a22fb86fdcfa2152fdba4349a617ad38a41ae39737f

test:
  secret_key_base: ab5c076880a1afabefa5b1ddc63bcff19e6851259833494c8d02e88fb5383fa0bf72adfa6eca94b0450fc72165af6700b3a83ae2c438bb28fea5ab22c07159fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
